@startuml "unsubscription sequence diagram"
skinparam shadowing false
skinparam monochrome reverse
autoactivate on
autonumber
activate Client
Client ->  Server: Request unsubscription
Server ->  Server: Process request infos
deactivate Server
Server --> Client: Send acknowledge
@enduml