@startuml UseCase
left to right direction
skinparam shadowing false
skinparam monochrome reverse

frame "uc: Use Content" {
    actor Visitor
    actor Registered

    Visitor <|-left- Registered

    package "Appreciate content" {
        (Report content)
        (Comment content)
        (Rate content)
        (Bookmark content)
    }

    package "Browse Content" {
        (List content)
        (Search content) <.down. (Filter content)
    }

    package "Open content" as OK {
        (Share content)
        (Resume content)
        (Watch content)
        (Manage note)
    }

    package "Moteur Arkad" as MAK {
    }

    (Watch content) .down.> MAK : <<extend

    package "Interact Profile" {
        (Subscribe author)
        (Report author)
    }

    :Visitor: -down- (List content)
    :Visitor: -down- (Search content)

    :Visitor: -down- (Share content)
    :Registered: -down- (Resume content)
    :Registered: -down- (Manage note)

    :Registered: -down- (Subscribe author)
    :Registered: -down- (Report author)

    :Visitor: -down- (Watch content)
    :Registered: -down- (Bookmark content)
    :Registered: -down- (Report content)
    :Registered: -down- (Comment content)
    :Registered: -down- (Rate content)
}

@enduml