@startuml UseCase
left to right direction
skinparam shadowing false
skinparam monochrome true

frame "uc: Use IDE" {
    actor User

    rectangle System {
        (Use code editor)
        (Use mini browser)
        (Use console)
        (Use file manager)
        (Use slide)
    }

    :User: -- (Use code editor)
    :User: -- (Use mini browser)
    :User: -- (Use file manager)
    :User: -- (Use slide)
}

@enduml