@startuml UseCase
left to right direction
skinparam shadowing false
skinparam monochrome reverse

frame "uc: Manage Account" {
    actor Creator
    actor Pro

    Creator <|-left- Pro

    package "Manage Account" {
        (View Analytics)
        (Edit account) <.right. (Upgrade account) : <<extend>>
        (Edit account) <.left. (Delete account) : <<extend>>
    }

    package "Manage Payment" {
        (Define billing method) -left- (Delete billing method) #line:white
        (Delete billing method) -left- (View billings) #line:white
    }

    package "Manage Note" {
        (Open note) -left- (Delete note) #line:white
        (Open note) -left- (Rename note) #line:white
    }

    :Creator: -down- (Edit account)
    :Creator: -down- (Delete account)
    :Creator: -down- (Upgrade account)

    :Pro: -down- (View Analytics)

    :Pro: -down- (Open note)
    :Pro: -down- (Delete note)
    :Pro: -down- (Rename note)

    :Pro: -down- (Define billing method)
    :Pro: -down- (Delete billing method)
    :Pro: -down- (View billings)
}

@enduml