@startuml UseCase
left to right direction
skinparam shadowing false
skinparam monochrome reverse

frame "uc: Manage Account" {
    actor Register
    actor Pro

    Register <|-left- Pro

    package "Manage Account" {
        (List bookmarks)
        (Edit account) <.down. (Upgrade account) : <<extend>>
        (Edit account) <.right. (Delete account) : <<extend>>
        (View billings)
    }

    package "Manage Note" {
        (Open note) -left- (Delete note) #line:white
        (Open note) -left- (Rename note) #line:white
    }

    :Register: -down- (Edit account)
    :Register: -down- (List bookmarks)

    :Pro: .down. (List bookmarks) #line:white

    :Pro: -down- (Open note)
    :Pro: -down- (Delete note)
    :Pro: -down- (Rename note)

    :Pro: -down- (View billings)
}

@enduml