@startuml UseCase
left to right direction
skinparam shadowing false
skinparam monochrome true

frame "uc: Manage Account" {
    actor Creator
    actor Pro

    Creator <|-left- Pro

    package "Manage Account" {
        (Edit account) <.left. (Upgrade account) : <<extend>>
        (Edit account) <.. (Delete account) : <<extend>>
        (Edit account) <|-down- (Pro Profile)
        (Edit account) <|-down- (School Profile)
        (Edit account) <|-down- (Business Profile)
    }
    
    package "Analytics" {
        (View Watched time)
        (View Most viewed)
        (View Top video)
        (View Subscriptions)
        (View Sales reports)
    }

    package "Manage Payment" {
        (Add billing method) -left- (Open billing method) #line:white
        (Open billing method) -left- (Change billing method) #line:white
        (Change billing method) -left- (Delete billing method) #line:white
        (Delete billing method) -left- (View billings) #line:white
        (View billings) <|-up- (Charts)
        (View billings) <|-up- (Lists)
    }

    package "Manage Note" {
        (Open note) -left- (Delete note) #line:white
        (Open note) -left- (Rename note) #line:white
    }

    :Pro: -up- (Open note)
    :Pro: -up- (Delete note)
    :Pro: -up- (Rename note)

    :Pro: -up- (Add billing method)
    :Pro: -up- (Open billing method)
    :Pro: -up- (Change billing method)
    :Pro: -up- (Delete billing method)
    :Pro: -up- (View billings)

    :Pro: -down- (View Watched time)
    :Pro: -down- (View Most viewed)
    :Pro: -down- (View Top video)
    :Pro: -down- (View Subscriptions)
    :Pro: -down- (View Sales reports)

    :Creator: -down- (Edit account)
    :Creator: -down- (Delete account)
    :Creator: -down- (Upgrade account)
}

@enduml