@startmindmap Apps
left to right direction
skinparam shadowing false
skinparam monochrome true

+ apps
++ admin
+++ components
+++ includes
+++ state
+++ views
++ clients
+++ account
++++ ...
+++ browse
++++ ...
+++ ...
+++ public
++++ ...
+++ record
++++ ...
++ shared
+++ assets
++++ images
++++ json
++++ scripts
++++ styles
++++ videos
+++ components
+++ constants
+++ layouts
+++ states

@endmindmap