@startuml
left to right direction
skinparam shadowing false
skinparam monochrome reverse

frame "uc: Pro Features" {
    actor Creator
    actor Pro

    :Pro: -left-|> :Creator:

    package "Moteur ARKAD" as MAK {
    }

    package "Plan Live" as PL {
        (Plan live kast)
        (Cancel live kast) <.up. (Change live kast plan)
    }

    package "Lead Live" as LL {
        (Authorize stream)
        (Browse viewer screen) <.down. MAK
        (Save live kast)
        (Stream live kast) <.down. MAK
    }

    PL -right- LL #line:white

    package "Assist Live" {
        (Ask to stream)
        (Watch live kast)
        (Chat live kast)
        (Multi-stream live kast) <.down. MAK
    }

    :Pro: -down- (Plan live kast)
    :Pro: -down- (Change live kast plan)

    :Pro: -down- (Authorize stream)
    :Pro: -down- (Browse viewer screen)
    :Pro: -down- (Save live kast)
    :Pro: -down- (Stream live kast)

    :Creator: -down- (Chat live kast)
    :Creator: -down- (Ask to stream)
    :Creator: -down- (Watch live kast)
    :Creator: -down- (Multi-stream live kast)
}
@enduml