@startuml UseCase
left to right direction
skinparam shadowing false
skinparam monochrome true

frame "us: Creator and Viewer" {
    actor Viewer
    actor Creator
    actor Visitor

    Viewer <|-left- Creator
    Visitor -right-|> Viewer

    rectangle System {
        (Log in)
        (Manage Note)
        (Manage Account)
        (Appreciate arkast)
        (Search arkast)
        (Watch arkast)
        (Register)
    }
    
    (Search arkast) .down.> (Watch arkast) : <<extend>>
    (Watch arkast) <.up. (Appreciate arkast) : <<extend>>
    
    :Creator: -- (Log in)
    :Creator: -- (Manage Note)
    :Creator: -- (Manage Account)
    :Creator: -- (Appreciate arkast)
    :Viewer: -- (Watch arkast)
    :Viewer: -- (Search arkast)
    :Visitor: -- (Register)
}

@enduml