@startuml UseCase
left to right direction
skinparam shadowing false
skinparam monochrome true

frame "uc: Creator - Manage Arkast List" {
    actor Creator

    rectangle System {
        (Create arkast)
        (Search arkast)
        (List arkasts)
        (Manage playlists)
        (Publy arkast)
        package "Use Arkad" as UA {

        }
    }
    (Search arkast) .left.> (List arkasts) : << include >>
    (Create arkast) <.. (Publy arkast) : << extend >>
    (Create arkast) ..> UA : << include >>

    :Creator: -- (Create arkast)
    :Creator: -- (Search arkast)
    :Creator: -- (List arkasts)
    :Creator: -- (Manage playlists)
}

@enduml