@startuml UseCase
left to right direction
skinparam shadowing false
skinparam monochrome true

frame "uc: Creator - Use Arkad" {
    actor Creator

    rectangle System {
        (Use code editor)
        (Use mini browser)
        (Use file manager)
        (Use slide)
    }
    :Creator: -- (Use code editor)
    :Creator: -- (Use mini browser)
    :Creator: -- (Use file manager)
    :Creator: -- (Use slide)
}

@enduml