@startuml UseCase
left to right direction
skinparam shadowing false
skinparam monochrome true

frame "uc: Viewer" {
    actor Viewer

    rectangle System {
        :Viewer: --> (Register)
        :Viewer: --> WA
        :Viewer: --> (Search arkast)

        (Search arkast) ..> WA : <<extend>>
        (Register) <|-- (Using google)
        (Register) <|-- (Using github)
        WA ..> UA : <<extend>>

        package "Watch Arkast" as WA {

        }

        package "Use Arkad" as UA {
            
        }
    }
}

@enduml