@startuml UseCase
left to right direction
skinparam shadowing false
skinparam monochrome true

frame "uc: Viewer Creator - Watch Arkast" {
    actor Viewer
    ' actor Creator

    rectangle System {
        :Viewer: --> (Play Arkast)
        :Viewer: --> (Pause Arkast)

        (Pause Arkast) <.. UA : <<extend>>
        (Pause Arkast) <.. CIP : <<extend>>

        package "Use Arkad" as UA {
        }

        package "Manage Note" as CIP {
        }
    }
}

@enduml