@startuml "subscription sequence diagram"
skinparam shadowing false
skinparam monochrome true
autoactivate on
autonumber
activate Client
loop while no access and no denial access
    Client ->  Server: Request subscription
    Server ->  Server: Process request infos
    alt exceeding the limit of subscription
        Server --> Client: Deny access
    else wrong format of subscription infos
        Server --> Client: Request new subscription infos
    else successful case
        Server --> Client: Authorization access
        Client ->  Server: Subcription complete
        Server ->  Server: Prepare a send flow
        deactivate Server
    end
end
ref over Client, Server : Cast new event

@enduml