@startuml "transfer event sequence diagram"
skinparam shadowing false
skinparam monochrome true
skinparam ParticipantPadding 5
skinparam BoxPadding 5
autoactivate on
autonumber
activate Recorder

box "Live Server"
    participant Recorder
    participant Bufferizer
end box

box "Live Client"
    participant Scheduler
    participant Player
end box
Recorder ->  Bufferizer : New Event
deactivate Recorder
Bufferizer ->  Bufferizer : Bufferize the event 
deactivate Bufferizer
loop buffer not empty
    Bufferizer -> Scheduler : Emit the event
    deactivate Bufferizer
    Scheduler -> Scheduler : Save the event
    deactivate Scheduler
    Scheduler -> Player : Trigger the action
    deactivate Player
    Scheduler -> Bufferizer : Send Acknowledge
    deactivate Scheduler
    Bufferizer ->  Bufferizer : Remove event
end

@enduml