@startuml "Manage content"
left to right direction
skinparam shadowing false
skinparam monochrome reverse

frame "uc: Manage Contents" {
    actor Creator
    actor Pro

    Creator <|-left- Pro

    package "Moteur ARKAD" as MAK {
    }

    package "Manage Arkast " {
        (Create kast)
        (Publish kast) <.right. (Schedule) : <<extend>>
        (List kast)
        (Publish kast) .right.> (Set visibility) : <<include>>
        (Set price)
        (Update kast) <.left. (Delete kast) : <<extend>>
        (Update kast)  <.down. MAK
        (Create kast)  <.. MAK : <<extend>>
    }
    
    package "Manage List" {
        (Create List) <|-down- (Simple)
        (Create List) <|-down- (Cursus)
        (List List)
        (Update List) <.down. (Delete List) : <<extend>>
    }

    :Pro: -down- (Schedule)
    :Pro: -down- (Set price)

    :Creator: -down- (Create kast)
    :Creator: -down- (Publish kast)
    :Creator: -down- (Update kast)
    :Creator: -down- (List kast)

    :Creator: -down- (Create List)
    :Creator: -down- (Update List)
    :Creator: -down- (List List)
}
@enduml