@startuml
left to right direction
skinparam shadowing false
skinparam monochrome reverse

frame "uc: Manage Basics Contents" {
    actor Creator
    actor Pro

    Creator <|-left- Pro

    package "Moteur ARKAD" as MAK {
    }

    package "Manage Arkast " {
        (Create kast)
        (Publish kast) <.left. (Schedule) : <<extend>>
        (List kast)
        (Update kast) <.left. (Delete kast) : <<extend>>
        (Update kast)  <.down. MAK
        (Create kast)  <.. MAK : <<extend>>
    }
    
    package "Manage Series" {
        (Create series)
        (List series)
        (Update series) <.down. (Delete series) : <<extend>>
    }

    package "Manage Cursus" {
        (Create cursus)
        (Edit cursus) <.down. (Delete cursus) : <<extend>>
        (List cursus)
    }

    :Pro: -down- (Schedule)
    :Pro: .down. (Publish kast) #line:white

    :Pro: -down- (Create cursus)
    :Pro: -down- (Edit cursus)
    :Pro: -down- (List cursus)

    :Creator: -down- (Create kast)
    :Creator: -down- (Publish kast)
    :Creator: -down- (Update kast)
    :Creator: -down- (List kast)

    :Creator: -down- (Create series)
    :Creator: -down- (Update series)
    :Creator: -down- (List series)
}
@enduml