@startuml
left to right direction
skinparam shadowing false
skinparam monochrome reverse

frame "uc: School Features" {
    actor Register
    actor Substitute
    actor Register

    note "Substitute can do\nall Register use cases\nexcept critical ones." as NOTE
    :Register: <|-up- NOTE
    NOTE -left- :Substitute:

    package "Manage Actor" {
        (Create Actor) <|-down- (Student)
        (Create Actor) <|-down- ( Substitute)
        (Edit Actor) <.down. (Block Actor) : <<extend>>
        (List Actor)
        (Delete Actor)
        (Open Actor)
    }

    package "Manage School" {
        (View Analytics)
        (Create School) <|-down- (FreeSchool)
        (Create School) <|-down- (BusinessSchool)
        (List School)
        (Edit School) <.down. (Block School) : <<extend>>
        (Delete School)
        (Subscribe School) <|-down- (Rank)
        (Subscribe School) <|-down- (Free)
        (Define rank)
    }

    :Register: -down- (Create Actor)
    :Register: -down- (Edit Actor)
    :Register: -down- (List Actor)
    :Register: -down- (Delete Actor)
    :Register: -down- (Open Actor)

    :Register: -down- (Create School)
    :Register: -down- (Edit School)
    :Register: -down- (List School)
    :Register: -down- (Delete School)
    :Register: -down- (View Analytics)
    :Register: -down- (Subscribe School)
    :Register: -down- (Define rank)

}
@enduml