@startuml
left to right direction
skinparam shadowing false
skinparam monochrome reverse

frame "uc: School Features" {
    actor School
    actor BusinessSchool
    actor Substitute
    actor Register

    note "Substitute can do\nall school use cases\nexcept critical ones." as NOTE
    :School: <|-up- NOTE
    NOTE -left- :Substitute:
    :School: <|-left- :BusinessSchool:
    :School: <|-right- :Register:

    package "Manage Actor" {
            (Create Actor) <|-down- (Student)
            (Create Actor) <|-down- ( Substitute)
            (Edit Actor)
            (Delete Actor)
            (Block Actor)
            (Open Actor)
    }

    package "Manage Selling" as MSE {
        (Sell content)
        (Define rank)
        (View sales report)
    }

    package "Manage Access" as MA {
        (Request access)
        (Restrict usage) <|-left- (For Accepted Register)
        (Restrict usage) <|-down- (For specific Label)
        (Restrict usage) <|-down- (For specific Student)
        (Deny access) <.down. (Block requester) : <<extend>>
        (Accept access)
    }

    package "Purchase" as UCO {
        (Buy content)
        (Subscribe rank)
    }

    :School: -down- (Create Actor)
    :School: -down- (Edit Actor)
    :School: -down- (Block Actor)
    :School: -down- (Delete Actor)
    :School: -down- (Open Actor)
    :School: -down- (Restrict usage)
    :School: -down- (Accept access)
    :School: -down- (Deny access)

    :Register: -down- (Request access)
    :Register: -down- (Buy content)
    :Register: -down- (Subscribe rank)

    :BusinessSchool: -down- (Sell content)
    :BusinessSchool: -down- (Define rank)
    :BusinessSchool: -left- (View sales report)
}
@enduml