@startuml UseCase
left to right direction
skinparam shadowing false
skinparam monochrome true

frame "uc: Manage Access" {
    actor Organizer
    actor Student
    actor Register

    package "Manage Room" {
        (Create room) -left- (Open room) #line:white
        (Open room) -left- (Close room) #line:white
        (Close room) -left- (List join request) #line:white
        (Enter room)
        (Request to join) <.down. (Respond to join) : <<extend>>
        (Share room) -right- (List join request) #line:white
        (List join request) <.left. (Open requester profile) : <<extend>>
        (Open requester profile) <.left. (Block requester) : <<extend>>
        (List join request) <.up. (Respond to join) : <<extend>>
        (Open requester profile) <.up. (Respond to join) : <<extend>>
        (Respond to join) <|-left- (Deny)
        (Respond to join) <|-right- (Accept)

        (Share room) <|-up- (Public)
        (Share room) <|-right- (Restricted)
        (Restricted) <|-right- (For Accepted Register)
        (Restricted) <|-up- (For specific Label)
        (Restricted) <|-up- (For specific Student)
    }

    :Student: -down- (Enter room)

    :Organizer: -up- (Share room)
    :Organizer: -up- (Create room)
    :Organizer: -up-  (Open room)
    :Organizer: -up-  (Close room)
    :Organizer: -up- (List join request)
    :Organizer: -up- (Open requester profile)
    :Organizer: -up- (Block requester)

    :Register: -down- (Request to join)
    :Register: -down- (Enter room)
}

@enduml