@startuml "player state diagram"
skinparam shadowing false
skinparam monochrome true

' frame "st: player state diagram" {
    [*] --> Init : arkast clicked
    Init --> Play : player is ready
    Interact --> Play : play button pressed
    Pause --> Play : play button pressed
    Play --> Pause : pause button pressed
    Pause --> Interact : use arkador
    Interact --> Pause : cancel modification
    Pause --> Exiting : quit player
    Play --> Exiting : quit player
    Interact --> Exiting : quit player
    state c <<choice>>
    Play --> c : arkast over
    c --> Init : [next arkast exist]
    c --> Exiting  : [next arkast not exist]
    Exiting --> [*] : quit the player
' }

@enduml