@startuml "player state diagram"
skinparam shadowing false
skinparam monochrome true

' frame "st: player state diagram" {
    [*] -down-> Init : arkast clicked
    Init --> Playing : play button pressed
    State Playing {
        [*] -down-> Play
        Play -down-> Pause : pause button pressed
        Pause -up-> Play : play button pressed
        Pause --> Interact : use arkador
        Interact --> Pause : cancel modification
        Interact --> Record : record interaction
        Record -right-> Handle : stop recording
        Handle -right-> Interact : back to interactive mode
    }
    Playing --> Exit : quit player
    Exit --> [*] : quit the player
' }

@enduml