@startuml "subscription activity diagram"
skinparam shadowing false
skinparam monochrome reverse
!pragma useVerticalIf on
partition "subscription activity diagram" {
    start
    : Processing request infos;
    if (exceeding the limit of subscription) then (yes)
        stop
    endif
    repeat : Processing request infos;
    backward: Request new subscription infos;
    repeat while (wrong format of subscription infos)
    : Authorization access;
    : Prepare a send flow;
    stop
}
@enduml