@startuml "Package diagram"
left to right direction
skinparam shadowing false
skinparam monochrome reverse

frame "pk: Different type of Profile" {
    actor Registered
    actor Pro
    actor Substitute
    actor Visitor
    actor Admin
    actor Student
    actor Manager

    Registered <|-up- Pro
    Pro <|-left- Substitute
    Visitor <|-right- Admin
    Admin <|-right- Manager
    Visitor <|-left- Student

    rectangle "Front-office" {
        ' package "Services" as SE {
            package "Manage Live" as MLI {
            }
            package "Use Content" as UCO {
            }
            package "Manage Content" as MCO {
            }
            package "Manage Access" as MAC {
            }
            package "Manage School" as MS {
            }
            package "Manage Account" as MAc {
            }
            MLI .left.> UCO
            MCO .right.> UCO
        ' }

        ' package "Security" as S {
        ' }

        ' SE .left.> S
    }

    :Pro: -left- MLI
    :Registered: -- MAc
    :Registered: -- MCO
    :Registered: -- UCO
    :Student: -up- MAc
    :Visitor: -left- UCO
    :Registered: -left- MAC
    :Registered: -right- MS

    rectangle "Back-office" {
        package "Manage Manager office" as _MAN {
        }
        package "Manage Arkast office" as _MA {
        }
        package "Manage User office" as _MU {
        }
        package "Manage Adds office" as _MAD {
        }
        package "Manage Billing office" as _MB {
        }
        package "Manage Reporting" as _MR {
        }
        package "Manage Claiming" as _MC {
        }
        package "Manage App" as _MAP {
        }

        _MR <|-right- _MC #line:white
        _MU .down.> _MR
        _MA .down.> _MR
        _MAD .down.> _MR
        _MB .down.> _MC
    }

    ' _SAP -- S
    :Admin: -down- _MAN
    :Admin: -down- _MAP
    :Admin: -down- _MA
    :Admin: -down- _MU
    :Admin: -down- _MAD
    :Admin: -down- _MB
}
@enduml