@startuml "Files Handler Component Diagram"
skinparam shadowing false
skinparam monochrome true

frame "cp: Files handler" {
    rectangle "Client Side"{
        [Compressor]
        [Decompressor]
        [Uploader]
        [Downloader]
        package "recorder" {
            [Recorder]
        }
        package player {
            [Player]
        }

        [Recorder] -up-> [Uploader]
        [Player] -up-> [Downloader]
    }
    rectangle "Server Side"{
        [FileHandler]
    }

    [Uploader] -right-> [Compressor]
    [Downloader] -left-> [Decompressor]
    [Uploader] -up-> [FileHandler]
    [Downloader] -up-> [FileHandler]
}
@enduml