@startuml "recorder component diagram"
skinparam shadowing false
skinparam monochrome true

frame "cp: Recorder" {
    [Recorder] <-down-> [Watchers]
    [Recorder] <-right-> [Listener]
    [Recorder] -up-> [NodeCaptor]
    [Recorder] <-left-> [MutationBuffer]
    [MutationBuffer] -down-> [NFMHandler]

    note bottom of [NFMHandler]
        NFM stand for
        Node Formated Map
    end note

    ' watchers - [Watcher]
    ' mirror - [Utils]
    ' nodeCaptor - [Captor]
    ' typesCaptor - [Captor]
    ' typesRecorder - [Recorder]
    ' [Watcher] --( mirror
    ' [Recorder] --( mirror
    ' [Recorder] -right-( nodeCaptor
    ' [Watcher] --( typesCaptor
    ' [Watcher] -down-( typesRecorder
    ' [Watcher] --( mutationBuffer
}
@enduml