@startuml "recorder component diagram"
skinparam shadowing false
skinparam monochrome true

frame "cp: Recorder" {
    [Recorder] <-down-> [Watchers]
    [Recorder] <-right-> [Listener]
    [Recorder] -up-> [NodeCaptor]
    [Recorder] <-left-> [MutationBuffer]
    [MutationBuffer] -down-> [NFMHandler]
}
@enduml