@startuml "Kast Editor Component Diagram"
skinparam shadowing false
skinparam monochrome reverse
skinparam componentStyle rectangle
skinparam component {
  FontSize 17
}

frame "cp: Kast Editor" {
    component "Player Core" {
        [Player]
    }

    component "Player Interface" {
        [PlayerController]
    }

    [PlayerController] .down.> [Player]

    collections Events
    file Audio
    [Player] -down-> Events

    component "Editor Interface" {
        [ChapterEndPoints]
        [ChapterList]
    }

    component "Editor Core" {
        collections Chapters
        [ChapterHandler] -left-> Chapters
        [Partitionner] -up-> Chapters
        [Partitionner] <|-down- [AudioPartitioner]
        [Partitionner] <|-right- [EventPartitioner]
    }
    
    [EventPartitioner] -right-> Events
    [AudioPartitioner] -right-> Audio

    [ChapterEndPoints] .left.> [PlayerController]
    Chapters .up.> [ChapterEndPoints]
    Chapters .up.> [ChapterList]
}
@enduml