@startuml "Player Component Diagram"
skinparam shadowing false
skinparam monochrome true
skinparam componentStyle rectangle
skinparam component {
  FontSize 18
}

frame "cp: Player" {
    component "Player Core" {
        [PlayerMachineState] .left.> [ActionsTimelineScheduler]
        [ActionsTimelineScheduler] .left.> [ActionTriggers]
        [Player] .up.> [StateEmitter]
        [StateEmitter] <.up. [PlayerMachineState]
        [ActionsTimelineScheduler] .down.> [PlayerDOM]
        [PlayerDOM] .down.> [NodeBuilder]
        [PlayerDOM] .left.> [NodeFormatedHandler]
    }

    component "Player Interface" {
        [PlayerScreen]
        [PlayerController]
    }
    [PlayerScreen] <.up. [NodeBuilder]
    [PlayerController] .up.> [Player]
}
@enduml