@startuml "Player Component Diagram"
skinparam shadowing false
skinparam monochrome true
skinparam componentStyle rectangle
skinparam component {
  FontSize 18
}

frame "cp: Player" {
    package "Player Core" {
        [Player] -up-> [ActionsTimelineScheduler]
        [ActionsTimelineScheduler] -up-> [ActionTriggers]
        [Player] -left-> [PlayerDOM]
        [Player] -right-> [PlayerMachineState]
        [ActionsTimelineScheduler] -down-> [PlayerDOM]
        [PlayerDOM] -left- [NodeBuilder]
        [PlayerDOM] -up- [NodeFormatedHandler]
    }

    package "Player Interface" {
        [PlayerScreen]
        [PlayerController] -down- [PlayerProgressBar]
        [PlayerController] -down- [PlayButton]
        [PlayerController] -down- [VolumeHandler]
    }
    [PlayerScreen] -up- [PlayerDOM]
    [PlayerController] -up-> [Player]
}
@enduml