@startuml "Live Server Component Diagram"
skinparam shadowing false
skinparam monochrome true

frame "cp: Live Server" {
    rectangle "Viewer Side"{
        [Scheduler] -up-> [C-Listerner]
        [Scheduler] -down-> [C-Emitter]
        [Scheduler] -right-> [Player]
    }
    rectangle "Streamer Side"{
        [Bufferizer] -up-> [S-Emitter]
        [Bufferizer] -down-> [S-Listerner]
        [Bufferizer] -left-> [Recorder]
    }

    [C-Listerner] <.left. [S-Emitter]
    [S-Listerner] <.right. [C-Emitter]
}

@enduml