@startuml "Custom Event Handling Component Diagram"
skinparam shadowing false
skinparam monochrome true

frame "cp: Custom Event Handling" {
    rectangle "Recording View" {
        actor "User" as U
        U -down-> [PlateformInterface]
        U -down-> [RecorderInterface]
        [RecorderCore] -down-> [CustomEventProvider]
        [PlateformInterface] <-down- [RecorderCore]
        [PlateformInterface] -down-> [NativeCore]
        [NativeCore] -left-> [CustomEventProvider]
        [RecorderCore] <-up- [RecorderInterface]
    }

    rectangle "Replaying View" {
        actor "Watcher" as W

        W -down-> [PlayerInterface]
        [PlayerCore] -left-> [CustomActionProvider]
        [PlayerCore] -right-> [PlateformState]
        [PlayerCore] <-up- [PlayerInterface]
        [PlayerCore] -down-> [InteractionCore]
    }
}

@enduml