@startuml "Interaction Package Component Diagram"
skinparam shadowing false
skinparam monochrome true

frame "cp: Interaction Package" {
    actor "Watcher" as W

    rectangle "Interaction Core" {
        collections InteractionPoint
        [InteractionHandler] -right-> InteractionPoint
    }

    [InteractionHandler] -down-> [RecorderCore]
    [InteractionHandler] -left-> [NativeCore]

    rectangle "Player Core" {
        [Player] -right-> [PlayerDOM]
    }

    rectangle "Player Interface" {
       [PlayerController]
       [PlayerScreen]
       [PlateformInterface]
    }

    [InteractionHandler] <-up- [Player]
    [PlayerScreen] -down- [PlayerDOM]
    [NativeCore] <-up-> [PlateformInterface]
    [PlayerController] -down-> [Player]
    W -down-> [PlayerController]
    W --> [PlateformInterface]
}
note "To handle the multi-timeline \n mode we must have a list of \n pair eventList and audio" as n1
@enduml